// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1beta1

import (
	"database/sql"

	"github.com/gobuffalo/pop/slices"
	"github.com/gofrs/uuid"
	externalRef1 "github.com/meshery/schemas/models/core"
)

// Role defines model for role.
type Role struct {
	ID externalRef1.GeneralId `db:"id" json:"id"`

	// CreatedAt Timestamp when the resource was created.
	CreatedAt   externalRef1.CreatedAt `db:"created_at" json:"created_at,omitempty" yaml:"created_at"`
	DeletedAt   sql.NullTime           `db:"deleted_at" json:"deleted_at,omitempty" yaml:"deleted_at"`
	Description externalRef1.Text      `json:"description,omitempty"`
	Metadata    slices.Map             `db:"metadata" json:"metadata"`
	Owner       uuid.UUID              `db:"owner" json:"owner"`
	RoleNames   externalRef1.RoleNames `json:"role_names,omitempty"`

	// UpdatedAt Timestamp when the resource was updated.
	UpdatedAt externalRef1.UpdatedAt `db:"updated_at" json:"updated_at,omitempty" yaml:"updated_at"`
}

// RoleHolderRequest defines model for roleHolderRequest.
type RoleHolderRequest struct {
	// Email email
	Email     externalRef1.Email     `json:"email"`
	RoleNames externalRef1.RoleNames `json:"role_names"`
}

// RolesKeychainsMapping defines model for rolesKeychainsMapping.
type RolesKeychainsMapping struct {
	ID externalRef1.GeneralId `db:"id" json:"id"`

	// CreatedAt Timestamp when the resource was created.
	CreatedAt  externalRef1.CreatedAt `db:"created_at" json:"created_at,omitempty" yaml:"created_at"`
	DeletedAt  sql.NullTime           `db:"deleted_at" json:"deleted_at,omitempty" yaml:"deleted_at"`
	KeychainId uuid.UUID              `db:"keychain_id" json:"keychain_id"`
	RoleId     uuid.UUID              `db:"role_id" json:"role_id"`

	// UpdatedAt Timestamp when the resource was updated.
	UpdatedAt externalRef1.UpdatedAt `db:"updated_at" json:"updated_at,omitempty" yaml:"updated_at"`
}

// RolesKeychainsMappingPage defines model for rolesKeychainsMappingPage.
type RolesKeychainsMappingPage struct {
	Page                   externalRef1.Number     `json:"page,omitempty"`
	PageSize               externalRef1.Number     `json:"page_size,omitempty"`
	RolesKeychainsMappings []RolesKeychainsMapping `json:"rolesKeychainsMappings,omitempty"`
	TotalCount             externalRef1.Number     `json:"total_count,omitempty"`
}

// RolesPage defines model for roles_page.
type RolesPage struct {
	Page       externalRef1.Number `json:"page,omitempty"`
	PageSize   externalRef1.Number `json:"page_size,omitempty"`
	Roles      []Role              `json:"roles,omitempty"`
	TotalCount externalRef1.Number `json:"total_count,omitempty"`
}
